---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sona-pt
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sona-pt
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get","list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sona-pt
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sona-pt
subjects:
- kind: ServiceAccount
  name: sona-pt
  namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-sona-pt
  namespace: kube-system
spec:
  selector:
    matchLabels:
      job: kube-sona-pt
  template:
    metadata:
      labels:
        job: kube-sona-pt
    spec:
      hostPID: true
      hostNetwork: true
      restartPolicy: Always
      serviceAccountName: sona-pt
      containers:
      - image: registry.gitlab.com/sonaproject/sona-pt-cni
        imagePullPolicy: IfNotPresent
        name: kube-sona-pt
        securityContext:
          privileged: true
        envFrom:
        - configMapRef:
            name: install-config
        command: ["/bin/sh"]
        args: ["-c", "/sona-pt-cni/install-pt.sh"]
        volumeMounts:
        - name: config-host
          mountPath: /pt-config
        - name: binary-host
          mountPath: /pt-binary
        - name: kubelet-config
          mountPath: /kubernetes
        - name: log-vol
          mountPath: /tmp
        readinessProbe:
          exec:
            command:
            - cat
            - /tmp/readiness
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: config-host
        hostPath:
          path: /etc/cni/net.d
      - name: binary-host
        hostPath:
          path: /opt/cni/bin
      - name: kubelet-config
        hostPath:
          path: /etc/kubernetes
      - name: log-vol
        hostPath:
          path: /var/log/cni-installer
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
